# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Agora iOS Tutorial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AgoraRtcEngine_iOS'

  # Pods for Agora iOS Tutorial

end
